version: '3'
services:
  web:
    build: 
      context: ./thumbnail-generator-ui
      args: 
        - REACT_APP_API=${REACT_APP_API}
        - REACT_APP_API_PORT=${REACT_APP_API_PORT}
        - REACT_APP_UI_PORT=${REACT_APP_UI_PORT}
    ports:
      - ${REACT_APP_UI_PORT}:${REACT_APP_UI_PORT}
  backend:
    build: ./thumbnail-generator-api
    environment: 
      API_PORT: ${API_PORT}
    ports: 
      - ${API_PORT}:${API_PORT}